### ISSUE TITLE
Varying linewidth is possible like OpenGL coding?

### ISSUE THREAD

**Issue by iPsych** [mcfletch/pyopengl#39] opened 2020-03-03 07:15 UTC
I found below code for direct OpenGL coding. 

```
GLfloat thickness;
for(int i=0;i<n-1;++i)
{
if(ThisIsTheLine[i]) //your truth function for vertex i->i+1
thickness=5.0;
else
thickness=1.0;
glLineWidth(thickness);
glBegin(GL_LINES);
glVertex3f(x[i],y[i],z[i]);
glVertex3f(x[i+1],y[i+1],z[i+1]);
glEnd();
}
glLineWidth(1.f);//reset
```

In python, currently the linewidth is implemented as below.
```
     px_scale = self.transforms.pixel_scale 
     width = px_scale * self._parent._width 
     GL.glLineWidth(max(width, 1.))
```

Is it possible to set glLineWidth individually, for lines drawed by VisPy implemented pyopengl code?

**Comment by boorishpea** [comment] 2020-03-09 22:59
I am having the same problem, line width is Always 2.0 no matter what value I set it to, however the opacity does seem to change if I change gllinewidth to 0.5 but still a width of 2.0

**Comment by boorishpea** [comment] 2020-03-09 23:17
I can't find the bug, can anyone help me hotfix this

**Comment by boorishpea** [comment] 2020-03-09 23:26
@mcfletch

**Comment by mcfletch** [comment] 2020-03-10 13:37
Sorry, I don't, myself, use VisPy (I just write a library that it uses). My strong suspicion is that anyone implementing a general lines geometry type will be setting the linewidth internal to that component. I would suggest asking on a VisPy specific group, potentially with a runnable script attached that shows what you are trying.

**Comment by boorishpea** [comment] 2020-03-10 15:52
@mcfletch I can report that the problem is not with VisPy which is built on PyOpenGL. I am having the same problem with PyOpenGL (using GLFW or Glut). I can recreate this with OpenGL version 1.4 and 2.1 but when I try 3.2 pyOpenGL throws an exception. I get the same line width problem as @iPsych . Line widths do not work! and are always a width of 2 no matter what I set it to. How ever changing the line width changes opacity of the lines instead of the width.

**Comment by boorishpea** [comment] 2020-03-10 15:53
If there is there anything that I can do to help you fix this bug please let me know here, I will be keeping an eye on this thread.

**Comment by boorishpea** [comment] 2020-03-10 15:59
without sending you the full code, this can be used to recreate

def drawOneLine(x1, y1, x2, y2):
glLineWidth(1.0)
glBegin(GL_LINES)
glVertex2f(x1, y1)
glVertex2f(x2, y2)
glEnd()

line width is 2.0

**Comment by boorishpea** [comment] 2020-03-10 16:26
@mcfletch 
GLFW Code: https://pastebin.com/v0HDtkq6
Screenshot: https://imgur.com/a/j1SprzV

**Comment by mcfletch** [comment] 2020-03-10 18:15
Modified your code to apply line-widths from 0 through 20 to successive lines I see the line widths running from 0 through (approximately 10) on my Ubuntu 18.04 machine. That is, I see a no-width line, then 9 increasingly larger lines, then 10 more of the same size suggesting a maximum line width of 10.

![Screenshot_20200310_140834](https://user-images.githubusercontent.com/476378/76344988-e86ae900-62d8-11ea-87e8-2cfdd7d31ee1.png)

**Comment by boorishpea** [comment] 2020-03-10 19:14
I can see from your screenshot that you too were also able to reproduce the bug. The line width the width of 1.0 is the same as the line with the width 2.0 only darker. None the lines in your screenshot has managed to achieve a width of 1.0

**Comment by boorishpea** [comment] 2020-03-10 19:16
@mcfletch I can see from your screenshot that you too were also able to reproduce the bug.  None the lines in your screenshot has managed to achieve a width of 1.0

**Comment by boorishpea** [comment] 2020-03-10 19:18
The first and second line in your screenshot both have a width of 2.0, but are slightly different in color

**Comment by boorishpea** [comment] 2020-03-10 19:20
The lines are being drawn strange, changes in color, lack of 1.0 width, artifacts such as borders on the lines

**Comment by boorishpea** [comment] 2020-03-10 19:26
I'm writing a custom programming language that can convert itself  to csharp, c++ and python, so far the OpenGL libraries for csharp and c++ function the same, but with this difference in python, I cannot support python until pyOpenGL resolves this issue.

**Comment by mcfletch** [comment] 2020-03-10 19:44
The effects you are describing sounds exactly an aliased line being rendered, and that's what I see when I look at the rendering. The "change in colour" is aliasing with the width 1 line being spread across the two pixels to either side of the line. If you move the line .5 up the 1-pixel line becomes a hard/sharp line. The borders on the lines would be aliasing at the edges.

My guess is that you are seeing a difference in the context setup, but I don't know what precisely is different between the context setups.

**Comment by boorishpea** [comment] 2020-03-10 20:05
Ok. Let's not get off topic, anti alias and line smoothing are not the issue. How do you explain being unable to draw a line with a width of 1.0 ? If you can do this, please, show me an example.

**Comment by boorishpea** [comment] 2020-03-10 20:05
@mcfletch Ok. Let's not get off topic, anti alias and line smoothing are not the issue. How do you explain being unable to draw a line with a width of 1.0 ? If you can do this, please, show me an example.

**Comment by boorishpea** [comment] 2020-03-10 20:15
![Screenshot_2](https://user-images.githubusercontent.com/17771678/76355223-c8085200-630b-11ea-8ba5-74751d146005.png)

width 1.0 actual 2.0
width 2.0 actual 2.0
width 3.0 actual 4.0

**Comment by boorishpea** [comment] 2020-03-10 20:21
@mcfletch @iPsych 

This issue can be closed.
The problem was glfw.window_hint(glfw.SAMPLES, 4)
This is likley a similar cause for @iPsych

**Comment by mcfletch** [comment] 2020-03-10 20:21
So the blend function is blending the background into the line at .5 on the first line, there's no blending on the second because the line covers the entire pixel there. On the third, the inner pixels are covered by the line in full, the outer two are half-covered and are blended with the background.

**Comment by mcfletch** [comment] 2020-03-10 20:22
Ah, you figured it out, great. Closing.

**Closed by mcfletch** 2020-03-10 20:22 UTC
