### ISSUE TITLE
Attempt to auto-detect wayland vs. x11 (egl vs. glx) on linux

### ISSUE THREAD

**Issue by mcfletch** [mcfletch/pyopengl#41] opened 2020-04-28 02:03 UTC
SourceForge ticket here: https://sourceforge.net/p/pyopengl/bugs/275/

The values I see people reporting for wayland sessions seem to be "wayland", "xwayland" (for the nested x server) and "" for cases where wayland isn't run by SDDM or the like. I'm going on the assumption that using the EGL API for xwayland is correct, but I haven't been able to get wayland working on my machines, so it's just a guess as to what is appropriate.

**Comment by a-anjos** [comment] 2020-05-13 18:05
This is what works for me, from the terminal:
``
$ PYOPENGL_PLATFORM="egl" python3 myprogram.py''
``
This doesn't work, i.e. setting inside `myprogram.py`:
``
os.environ["PYOPENGL_PLATFORM"] = "egl"
``

I'll test your fix if you let me know how to do it without messing up my currently pip3 installed pyopengl.

**Comment by totaam** [comment] 2020-05-24 09:07
[xisxwayland](https://gitlab.freedesktop.org/xorg/app/xisxwayland/) may help: _tool to be used within shell scripts to determine whether the X server in use is Xwayland_

**Comment by adabru** [comment] 2021-03-29 11:05
Hi, I tried out the develop branch with the [pyqtgraph](https://github.com/pyqtgraph/pyqtgraph) examples, running `python -m pyqtgraph.examples`. They are qt based, my observation is following:

- When using sway compositor, the application starts as wayland application and the examples work perfectly.
- When using the reference weston compositor, the application starts as xwayland application by default and the examples fail. I can start the application with the prefix `QT_QPA_PLATFORM=wayland` and it will work perfectly as well.

Thing is, on weston I could use the command `python -m pyqtgraph.examples` without any environment variables set before. Now, on the develop branch, I have to set either `QT_QPA_PLATFORM=wayland` or `PYOPENGL_PLATFORM=x11`. So this could be a regression. But I guess qt will anyways default to wayland on weston somewhere along the way. Sway already does, I'm not sure what is currently the case with e.g. gnome.

For my use case the fix is perfect, there seems to be a possibility that on some compositors qt applications may fail if `QT_QPA_PLATFORM=wayland` is not set.

@a-anjos you can use following commands to leave your python environment untouched:

```
python -m venv .venv
source .venv/bin/activate
pip list
git clone --depth 1 --no-single-branch https://github.com/mcfletch/pyopengl.git
cd pyopengl
git checkout develop
pip install .
pip list
```

@mcfletch, if you want to test something out under wayland, you could try following steps (mainly taken from a [fedora HowTo](https://fedoraproject.org/wiki/How_to_debug_Wayland_problems)):

- Boot into an arbitrary linux desktop.
- Install your distribution's weston package (pacman, dnf, apt-get, ...). According to the fedora HowTo weston is the reference compositor to check your application against.
- Switch into another VTE by pressing ctrl+alt+fx.
- Run weston-launch (you can quit the session by pressing ctrl+alt+backspace).
- Click on the weston-terminal and run your python program.
- For example `pip install pyqt5 pyqtgraph && QT_QPA_PLATFORM=wayland python -m pyqtgraph.examples`, "3D Graphics" → "Scatter Plot".

I'm coming from issue https://github.com/pyqtgraph/pyqtgraph/issues/1661 and would be glad if the develop branch will be merged and released.

**Closed** 2022-02-19 22:46 UTC
